import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{background:'#000'}}
      >
        <header className="bg-scale-900 text-white p-4 text-center">
     <p>Welcome to next.js 15  demo  project</p>
        </header>
        <div className="h-80">

        {children}
        </div>
        <footer className="bg-scale-900 text-white p-4 text-center " >
         CodeEvolution
        </footer>
      </body>
    </html>
  );
}
